- name: Change the VM hostname
  ansible.windows.win_hostname:
    name: "{{ HOSTNAME }}"
  register: res

- name: Reboot VM after rename
  ansible.windows.win_reboot:
  when: res.reboot_required

- name: Wait for the hosts network interface to come back up
  local_action:
    module: wait_for
    host: "{{ ansible_host }}"
    port: "{{ WINRM_PORT }}"
    delay: 10
    state: started
  register: wait_result

- name: Install ADDS Role
  ansible.windows.win_domain_controller:
    dns_domain_name: "{{ DNS_DOMAIN_NAME }}"
    domain_admin_user: "{{ DOMAIN_ADMIN_USER }}"
    domain_admin_password: "{{ DOMAIN_ADMIN_PASSWORD }}"
    safe_mode_password: "{{ SAFE_MODE_PASSWORD }}"
    state: domain_controller

- name: Reboot after ADDS install
  ansible.windows.win_reboot:
  when: domain_controller.reboot_required

- name: Create new Root OU
  community.windows.win_domain_ou:
    name: "{{ ROOT_OU_NAME }}"
    state: present

- name: Create new Server OU
  community.windows.win_domain_ou:
    name: "{{ SERVER_OU_NAME }}"
    path: "{{ SERVER_OU_PATH }}"
    state: present

- name: Create new Users OU
  community.windows.win_domain_ou:
    name: "{{ USERS_OU_NAME }}"
    path: "{{ USERS_OU_PATH }}"
    state: present

- name: Create new AD Group in Users OU
  community.windows.win_domain_group:
    name: "{{ AD_GROUP_NAME }}"
    scope: global
    path: "{{ USERS_OU_PATH }}"
