- name: Change the VM hostname
  ansible.windows.win_hostname:
    name: "{{ HOSTNAME }}"
  register: res

- name: Reboot VM after rename
  ansible.windows.win_reboot:
  when: res.reboot_required

- name: Create new Domain/Forest
  ansible.windows.win_domain:
    dns_domain_name: "{{ DNS_DOMAIN_NAME }}"
    safe_mode_password: "{{ SAFE_MODE_PASSWORD }}"
    state: domain_controller
  register: domain_controller

- name: Reboot after ADDS install
  ansible.windows.win_reboot:
  when: domain_controller.changed

- name: Create new Root OU
  community.windows.win_domain_ou:
    name: "{{ ROOT_OU_NAME }}"
    state: present

- name: Create new Server OU
  community.windows.win_domain_ou:
    name: "{{ SERVER_OU_NAME }}"
    path: "{{ SERVER_OU_PATH }}"
    state: present

- name: Create new Users OU
  community.windows.win_domain_ou:
    name: "{{ USERS_OU_NAME }}"
    path: "{{ USERS_OU_PATH }}"
    state: present

- name: Create new AD Group in Users OU
  community.windows.win_domain_group:
    name: "{{ AD_GROUP_NAME }}"
    scope: global
    path: "{{ USERS_OU_PATH }}"
